### ISSUE TITLE
Should a millipede of size 0 (no body at all) be allowed?

### ISSUE THREAD

**Issue by tusbar** [getmillipede/millipede-rfc#2]
I would expect a millipede to have a minimum size of 1, so it has a body.

For reference, here’s a reversed millipede of size 1:

``` text
   ╔═(███)═╗
     ╔⊙ ⊙╗
```

A millipede of size 0 would only include the head.

**Comment by rockyluke** [comment]
According to wikipedia, it's no possible. One other thing, it seems that the millipede is finite (no infinite size).

**Comment by tusbar** [comment]
:bug: :D
